github:
patreon: 
open_collective:
ko_fi: 
tidelift:
community_bridge: 
liberapay: 
issuehunt: 
otechie: 
lfx_crowdfunding:
custom: ['https://youtube.com/@xtrememc8661', 'https://twitter.com/@Yassine_XT8661']
